name: zelda
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: mseeks/zelda
  name: zelda
  build_command: poetry install
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  routes:
  - path: /